# Generated by Django 4.0.2 on 2022-03-20 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menucard', '0005_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('header', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('bgcolor', models.CharField(blank=True, max_length=100)),
                ('mycolor', models.CharField(blank=True, max_length=100)),
                ('catcolor', models.CharField(blank=True, max_length=100)),
                ('bgimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
