# Generated by Django 4.0.2 on 2022-03-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucard', '0007_category_hotel_item_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='mobile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='whatsapplink',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
