# Generated by Django 4.0.2 on 2022-03-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menucard', '0007_category_hotel_item_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hotel',
        ),
    ]
