# Generated by Django 4.0.2 on 2022-03-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucard', '0012_alter_category_options_category_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='messgage',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
