# Generated by Django 4.0.2 on 2022-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucard', '0013_hotel_messgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='messgage',
            new_name='message1',
        ),
        migrations.AddField(
            model_name='hotel',
            name='message2',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
