# Generated by Django 4.0.2 on 2022-03-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucard', '0014_rename_messgage_hotel_message1_hotel_message2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='bordercolor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
