# Generated by Django 4.0.2 on 2022-03-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menucard', '0015_hotel_bordercolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
