# Generated by Django 4.0.2 on 2022-03-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucard', '0016_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='pureveg',
            field=models.BooleanField(default=True),
        ),
    ]
