# Generated by Django 4.0.2 on 2022-02-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_uploadfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_name',
            field=models.FileField(upload_to='csvs'),
        ),
    ]
